---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: admin
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:0.34.0
spec:
  releaseName: prometheus-operator
  chart:
    # Helm Charts: https://github.com/helm/charts/tree/master/stable/prometheus-operator
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus-operator
    version: 8.5.2
  valueFileSecrets:
    - name: prometheus-operator
  values:
    image:
      repository: quay.io/prometheus/alertmanager
      tag: 0.34.0
      pullPolicy: IfNotPresent

#    Injected by Flux - using secrets
#    grafana:
#      ingress:
#        enabled: true
#        annotations:
#          kubernetes.io/ingress.class: alb
#          alb.ingress.kubernetes.io/scheme: internet-facing
#          alb.ingress.kubernetes.io/target-type: ip
#          alb.ingress.kubernetes.io/healthcheck-path: "/metrics"
#          alb.ingress.kubernetes.io/certificate-arn: ${certificate_arn}  # Replace
#          alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
#        hosts:
#          - mgmt.${domain_name} # Replace
#        path: /*
#      env:
#        GF_SERVER_ROOT_URL: https://mgmt.${domain_name}/  # Replace
#      # force chart to generate password as prometheus-operator-grafana secret
#      adminPassword: null